### ISSUE TITLE
Cannot find module 'event-kit'

### ISSUE THREAD

**Issue by phlizik** [Qix-/hix#1]
Cannot find module 'event-kit'
Hide Stack Trace
Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/alexphilzik/.atom/packages/hix/lib/hix-editor.coffee:1:25)
    at Object.<anonymous> (/Users/alexphilzik/.atom/packages/hix/lib/hix-editor.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/alexphilzik/.atom/packages/hix/lib/hix.coffee:2:13)
    at Object.<anonymous> (/Users/alexphilzik/.atom/packages/hix/lib/hix.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:207:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:876:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:240:20)

**Comment by Qix-** [comment]
Hmm, could you try re-installing this package? `event-kit` is still very much available and it's listed in my package.json file.

**Comment by DerPferd** [comment]
Same problem. Using atom 1.12.7

**Comment by Qix-** [comment]
Should be fixed.

So I realized when you opened this issue that I never finished the project. As of now, it just dumps binary data into a hex editor-like view; you can't edit the binary data (yet).

While I was fixing this, I added another context menu item when right clicking on the file tree items (`Open in Hex Editor`).

I'll spend some time today re-vamping this module to be more efficient, as opening large binary files (e.g. images) will slow your editor to a halt.

Give me some time :)

**Comment by Qix-** [comment]
Should be fixed on latest master!
