### ISSUE TITLE
Uncaught TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by ACqua42** [Qix-/hix#2]
[Enter steps to reproduce:]

1. Installed his inside Atom.
2. To try it out: in a new file I write ABCabc123
3. Select hix from the package menu

Sorry, completely new to Atom, so can probably not answer very specific questions. But a need a hex editor!!! (Usually, I am using Ultraedit on Windows.)

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [hix](https://github.com/qix-/hix) package 0.1.0

### Stack Trace

Uncaught TypeError: path must be a string or Buffer

```
At fs.js:303

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.readFile (fs.js:303:11)
    at Object.fs.readFile (ELECTRON_ASAR.js:451:25)
    at /packages/hix/lib/hix-editor.coffee:10:6)
    at Object.toggle (/packages/hix/lib/hix.coffee:40:32)
    at /packages/hix/lib/hix.coffee:15:76)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1179:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:05.0 core:confirm (input.hidden-input)
  2x -0:33.9.0 hix:toggle (div.package-detail.panels-item)
```

### Non-Core Packages

```
atom-clock 0.1.6 
hix 0.1.0 
```

**Comment by Qix-** [comment]
Did you save the file first? :) This is a known problem. Atom doesn't store the binary contents in a buffer anywhere; only the path and the _text_ contents (which aren't necessarily the same as the binary contents).

Save the file first and then try again and let me know :)

**Comment by ACqua42** [comment]
Just tried it on a Windows 10 - same issue. But you are right, it works if the buffer is saved.
Thanks a lot! Now Im waiting for the edit mode ;-)

**Comment by Qix-** [comment]
Awesome :) I'll ping this issue when I have it added.
